### ISSUE TITLE
Campos obrigatórios para o PagSeguro?

### ISSUE THREAD

**Issue by andersonchagas** [claudiosanches/wc-digital-goods-checkout#2]
Pagando com pagseguro ele não finaliza pois pede alguns campos obrigatórios.

![image](https://cloud.githubusercontent.com/assets/1184508/23223487/f7d34018-f909-11e6-8623-b6541afc7ac4.png)

É um requisito do pagseguro?

**Comment by claudiosanches** [comment]
Se for apenas pagamento no site do PagSeguro não tem problema, se for checkout transparente vai precisar de todos os campos.
