### ISSUE TITLE
CPF e CPNJ para produtos digitais

### ISSUE THREAD

**Issue by dianaszankowski** [claudiosanches/wc-digital-goods-checkout#5]
Olá,
Eu uso o seu plugin Brazilian Market on WooCommerce para capturar CPF e CNPJ mas só vendo produtos digitais, não possuo a necessidade de capturar endereço dos clientes. Tentei usar o seu outro plugin Digital Goods Checkout on WooCommerce, mas ele esconde o CPF e CNPJ e apresar de ser produto digital, preciso dessas informações para emitir nota fiscal para o cliente.
Seria possível termos a opção de escolhermos se queremos capturar o CPF e o CNPJ? 
Testei vários plugins de checkout fields mas não consigo achar um que não dê conflito com o Brazilian Market on WooCommerce.
Obrigada
Diana

**Comment by claudiosanches** [comment]
Este plugin aqui vai remover todos os campos, se você quer deixar algum, melhor usar outro plugin para remover os campos que você não quer.

**Comment by dianaszankowski** [comment]
Oi Claudio,
Obrigada pela resposta.
Então, o problema é que eu não estou conseguindo achar nenhum outro plugin de checkout fields que não conflite com o Brazilian Market on WooCommerce. Já testei vários, ou eles removem os campos de CPF e CNPJ ou bagunçam a ordem dos campos de checkout.
Daí pensei que poderia te dar essa sugestão, porque apesar de ser um produto digital que estou vendendo e não precisar do endereço do cliente, ainda assim preciso emitir nota e para emitir nota preciso do CPF ou CNPJ.
Se em updates futuros você puder considerar essa opção, eu agradeceria muito.
Muito obrigada
Diana
